# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-07-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0028_auto_20200617_2337"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproposal",
            name="private_content_urls",
            field=models.BooleanField(
                default=False,
                help_text="Check it if you want to make your content URLs private",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="private_content_urls",
            field=models.BooleanField(
                default=False,
                help_text="Check it if you want to make your content URLs private",
            ),
        ),
    ]
